# Site settings
title: The Privacy and Civil Liberties Oversight Board
description: Committed to the protection of civil liberties and privacy in the nation's efforts against terrorism.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pclob.gov" # the base hostname & protocol for your site
logo: /assets/img/Great_Seal_of_the_United_States.svg
feature_image: /assets/img/aerial_capitol3.jpg

colors:
  background: '#ffffff'
  link:
    color: '#0071bc'
    active: '#0071bc'
    hover: '#205493'
    visited: '#0071bc'
  button:
    background: '#0071bc'
    hover: '#205493'
    text: '#fff'
  headers: '#205493'
  text: '#212121'
  reverse_text: '#ffffff'
  projects:
    accent: '#02bfe7'
    card-heading: '#0071bc'
  banner:
    background: '#112e51'
    text: '#fff'
    button:
      background: '#dce4ef'
      text: '#112e51'
  footer:
    primary-background: '#f1f1f1'
    secondary-background: '#d6d7d9'
    text: '#212121'

analytics:
  google:
    code: 'UA-48605964-32' # Change this to your GSA analytics code
  dap:
    agency: PCLOB    # Change this to your agency
    subagency: # Change this to your agency

defaults:
 -
  scope:
    path: "" # an empty string here means all files in the project
  values:
    layout:
      - home
      - page
      - "project-list"
      - project
      - "team-list"
      - team

footer:
  links:
      - text: 'Home'
        href: '#'
      - text: 'About'
        href: '#'
      - text: 'Reports'
        href: '#'
      - text: 'Events and press'
        href: '#'
  ancillary:
    - text: 'FOIA information'
      href: '#'
    - text: 'Plain Writing Act'
      href: '#'
    - text: 'USA.gov'
      href: 'https://usa.gov'
    - text: 'OSC.gov'
      href: 'https://osc.gov'

  image: /assets/img/Great_Seal_of_the_United_States.svg
  contact:
    name: Contact PCLOB
    phonenumber: (202) 331-1986
    address: MS2 – 2C104, Washington, DC 20511
    email: info@pclob.gov
    twitter:
      - PCLOB_GOV
  text: This site was built using <a href="https://federalist.18f.gov/" target="_blank">Federalist, from 18F</a>. # Change to a tag line for your agency

# Build settings
markdown: kramdown
include:
  - _navigation.json
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md

# Inititalize project and team collections
collections:
  reports:
    output: true
  board:
    output: true

wds-version: 1.1.0

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
